export * from './user';
export * from './medecin';
export * from './creneaux';
export * from './patient';
export * from './rendez_vous';
export * from './rendez_vousmedecin';
export * from './prescription1';
export * from './medicament';
export * from './ordonnance';
export * from './visite';
export * from './acteur';
export * from './dossier_patient';
export * from './details';
export * from './rendezVousAdmin';
export * from './ordonnancePharmacien'
export * from './facture'